[package]
name = "helium-wallet"
version = "1.6.11-dev"
authors = ["Helium <info@helium.com>"]
edition = "2021"
build = "build.rs"

description = "A Rust Helium Wallet library"
readme = "README.md"
keywords = ["helium", "blockchain", "wallet"]

homepage = "https://developer.helium.com/blockchain/blockchain-cli"
repository = "https://github.com/helium/helium-wallet-rs"

license = "Apache-2.0"

[[bin]]
name = "helium-wallet"
path = "src/main.rs"
doc = false

[dependencies]
anyhow = "1.0"
byteorder = "1.3.2"
structopt = "0.3"
dialoguer = "0.8"
sodiumoxide = "~0.2"
hex = "0.4"
hmac = "0"
sha2 = "0"
base64 = "0"
reqwest = {version = "0", default-features=false, features=["rustls-tls"]}
pbkdf2 = {version = "0", default-features=false }
aes-gcm = "0"
shamirsecretsharing = {version="0.1.4", features=["have_libsodium"]}
prettytable-rs = "0.10"
lazy_static = "1"
regex = "1"
rand = "0.8"
qr2term = "0.2"
serde =  "1"
serde_derive = "1"
serde_json = "1"
rust_decimal = {version = "1", features = ["serde-float"] }
h3ron = "^0.10"
geo-types = "^0.6" # pinned by h3ron but required here for geo_types::Point
helium-api = "3"
angry-purple-tiger = "0"
helium-crypto = {git = "https://github.com/helium/helium-crypto-rs", tag="v0.3.1"}
helium-proto = { git = "https://github.com/helium/proto", branch="master"}
tokio = {version = "1", features = ["full"]}
bitvec = "*" # inherits from elliptic-curve crate

[dev-dependencies]
bs58 = "0.4"
